# CI stages to execute against all branches on PR merge
name: auto_cherry_pick_commits

on:
  pull_request_target:
    types: [closed]

# Github & Parent PR Env vars required
env:
  assignee: ${{ github.event.pull_request.assignee.login }}
  title: ${{ github.event.pull_request.title }}
  number: ${{ github.event.number }}
  is_dependency: ''

jobs:

  # Auto CherryPicking and Failure Recording for further use
  auto-cherry-pick:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CherryPick')
    name: Auto Cherry Pick to labeled branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}

    steps:
      ## Robottelo Repo Checkout
      - uses: actions/checkout@v3
        if: ${{ startsWith(matrix.label, '6.') && matrix.label != github.base_ref }}
        with:
          fetch-depth: 0

      ## Set env var for dependencies label PR
      - name: Check if the PR is a dependency PR
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: |
          echo "is_dependency=dependencies" >> $GITHUB_ENV
          echo $GITHUB_ENV

      ## CherryPicking and AutoMerging
      - name: Cherrypicking to zStream branch
        id: cherrypick
        if: ${{ startsWith(matrix.label, '6.') && matrix.label != github.base_ref }}
        uses: jyejare/github-cherry-pick-action@main
        with:
          token: ${{ secrets.CHERRYPICK_PAT }}
          branch: ${{ matrix.label }}
          labels: |
            Auto_Cherry_Picked
            ${{ matrix.label }}
            No-CherryPick
            ${{ env.is_dependency }}
          assignees: ${{ env.assignee }}
